/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dandelion.glb 
Author: Everton Bohnenberger (https://sketchfab.com/BOHNEN)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dandelion-46afdf378dc947d59f70e3ff5ede3e4d
Title: Dandelion
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dandelion.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.647, -0.153, 0.256]} rotation={[2.121, -0.094, 0.424]} scale={5.316}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.002']} position={[0.233, 0.051, 0]} rotation={[0, 0, 0.072]} scale={[1.205, 1.519, 1.203]} />
    </group>
  )
}

useGLTF.preload('/dandelion.glb')
