/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hibiscus1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hibiscus1.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.pSphere19_Material003_0001.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.pSphere19_Material003_0001_1.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.petals004.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.stalk001.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.pCylinder2_Material004_0.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.pCylinder2_Material004_0_1.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.pollen001.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/hibiscus1.glb')
