/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ixora.glb 
Author: PlantCatalog (https://sketchfab.com/PlantCatalog)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/realistic-hd-chinese-jungle-geranium-210-268a0cc517c24094b66b27b6b8047d7c
Title: Realistic HD Chinese jungle geranium (2/10)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ixora.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_leaf_01b_0.geometry} material={materials.Ixora_leaf_01b} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_flower_01_0.geometry} material={materials.Ixora_flower_01} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_tube_0.geometry} material={materials.Ixora_tube} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_flower_stalk_2_0.geometry} material={materials.Ixora_flower_stalk_2} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_flower_02_0.geometry} material={materials.Ixora_flower_02} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_flower_03_0.geometry} material={materials.Ixora_flower_03} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_leaf_01e_0.geometry} material={materials.Ixora_leaf_01e} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_leaf_01f_0.geometry} material={materials.Ixora_leaf_01f} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_branches_0.geometry} material={materials.Ixora_branches} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_bud_0.geometry} material={materials.Ixora_bud} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_flower_stalk_1_0.geometry} material={materials.Ixora_flower_stalk_1} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_twig_0.geometry} material={materials.Ixora_twig} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_leaf_01d_0.geometry} material={materials.Ixora_leaf_01d} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_leaf_01a_0.geometry} material={materials.Ixora_leaf_01a} />
      </group>
    </group>
  )
}

useGLTF.preload('/ixora.glb')
