/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lotus.glb 
Author: Kigha (https://sketchfab.com/Kigha)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-lotus-flower-12768caa111f446b8796e70f9cc53a23
Title: Stylized Lotus Flower
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/lotus.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Flower_Lotus-Stylized_Lotus_0'].geometry} material={materials.Lotus} position={[0, 0.755, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/lotus.glb')
