/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 orchid.glb 
Author: Lassi Kaukonen (https://sketchfab.com/thesidekick)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/orchid-flower-75d19624c0d04b65975e011a04ae77a0
Title: Orchid flower
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/orchid.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Orchid_Highpoly} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Orchid_Highpoly} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Orchid_Highpoly} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Orchid_Highpoly} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Orchid_Highpoly} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Orchid_Highpoly} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Orchid_Highpoly} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Orchid_Highpoly} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Orchid_Highpoly} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Orchid_Highpoly} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Orchid_Highpoly} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Orchid_Highpoly} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Orchid_Highpoly} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Orchid_Highpoly} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Orchid_Highpoly} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Orchid_Highpoly} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Orchid_Highpoly} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Orchid_Highpoly} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Orchid_Highpoly} />
      </group>
    </group>
  )
}

useGLTF.preload('/orchid.glb')
