/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tulip.glb 
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/generic-tulip-flower-d75f531255ad47a99051a4c421c8861b
Title: Generic tulip flower
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tulip.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-16.207, 0.06, -31.652]} rotation={[-1.463, -0.068, -0.304]} scale={100}>
          <mesh geometry={nodes.Cylinder002_tulip_opague_1_0.geometry} material={materials.tulip_opague_1} />
          <mesh geometry={nodes.Cylinder002_tulip_transparent_1_0.geometry} material={materials.tulip_transparent_1} />
        </group>
        <group position={[169.141, 0.06, -31.652]} rotation={[-1.602, 0.104, 0.953]} scale={100}>
          <mesh geometry={nodes.Cylinder001_tulip_opague_1_0.geometry} material={materials.tulip_opague_1} />
          <mesh geometry={nodes.Cylinder001_tulip_transparent_1_0.geometry} material={materials.tulip_transparent_1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tulip.glb')
