/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Daisy.glb 
Author: evolveduk (https://sketchfab.com/evolveduk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/daisy-bb3f6ca7d00a489b9a356fb88f011565
Title: Daisy
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Daisy.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Tree_0_Tree_0Mat_0.geometry} material={materials.Tree_0Mat} />
        <mesh geometry={nodes.Tree_1_Tree_1Mat_0.geometry} material={materials.Tree_1Mat} />
        <mesh geometry={nodes.Tree_2_Tree_2Mat_0.geometry} material={materials.Tree_2Mat} />
      </group>
    </group>
  )
}

useGLTF.preload('/Daisy.glb')
