/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Source: https://sketchfab.com/3d-models/sunflower-3a9514b8df044abe809432201b8f1c6e
*/

import * as THREE from "three";
import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber/native";
import { useSharedValue, withTiming } from "react-native-reanimated";

const Sunflower = (props: any) => {
  const { onFlowerClick, ...rest } = props;
  const y = useSharedValue(0);
  const group = useRef<THREE.Group>(null);

  // โหลดโมเดล sunflower.glb
  const { nodes, materials } = useGLTF(
    require("../../assets/models/Daisy.glb")
  ) as any;

  // ตั้งค่า animation ให้หมุนทีละนิด
  useEffect(() => {
    y.value = withTiming(2, { duration: 2000 });
  }, []);

  useFrame(() => {
    if (group.current) {
      group.current.rotation.set(0, y.value, 0);
    }
  });

  return (
      <group {...props} dispose={null}>
      <group position={[0, -1, 0]} scale={0.03}>
        <mesh
          geometry={nodes.Tree_0_Tree_0Mat_0.geometry}
          material={materials.Tree_0Mat}
        />
        <mesh
          geometry={nodes.Tree_1_Tree_1Mat_0.geometry}
          material={materials.Tree_1Mat}
        />
        <mesh
          geometry={nodes.Tree_2_Tree_2Mat_0.geometry}
          material={materials.Tree_2Mat}
        />
      </group>
    </group>
  );
};

export default Sunflower;


// โหลดโมเดลล่วงหน้า
useGLTF.preload(require("../../assets/models/sunflower.glb"));






/////// ปรับแต่งให้โมเดลไม่ใหญ่เกินไป model ขึ้นแล้ว แต่โมเดลใหญ่เกินไป
///ทำให้ model สามารถกดได้แล้วแสดงโครงงสร้างต่างๆของพืช