/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Source: https://sketchfab.com/3d-models/sunflower-3a9514b8df044abe809432201b8f1c6e
*/

import * as THREE from "three";
import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber/native";
import { useSharedValue, withTiming } from "react-native-reanimated";

const Sunflower = (props: any) => {
  const { onFlowerClick, ...rest } = props;
  const y = useSharedValue(0);
  const group = useRef<THREE.Group>(null);

  // โหลดโมเดล sunflower.glb
  const { nodes, materials } = useGLTF(
    require("../../assets/models/hibiscus.glb")
  ) as any;

  // ตั้งค่า animation ให้หมุนทีละนิด
  useEffect(() => {
    y.value = withTiming(2, { duration: 2000 });
  }, []);

  useFrame(() => {
    if (group.current) {
      group.current.rotation.set(0, y.value, 0);
    }
  });

  return (
  <group ref={group} {...rest} dispose={null} position={[0, -2.5, 0]} scale={0.5}>
        <mesh geometry={nodes.pSphere19_Material003_0001.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.pSphere19_Material003_0001_1.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.petals004.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.stalk001.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.pCylinder2_Material004_0.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.pCylinder2_Material004_0_1.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.pollen001.geometry} material={materials['Material.002']} />
    </group>
  );
};

export default Sunflower;


// โหลดโมเดลล่วงหน้า
useGLTF.preload(require("../../assets/models/hibiscus.glb"));

