/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Source: https://sketchfab.com/3d-models/sunflower-3a9514b8df044abe809432201b8f1c6e
*/

import * as THREE from "three";
import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber/native";
import { useSharedValue, withTiming } from "react-native-reanimated";

const Sunflower = (props: any) => {
  const { onFlowerClick, ...rest } = props;
  const y = useSharedValue(0);
  const group = useRef<THREE.Group>(null);

  // โหลดโมเดล sunflower.glb
  const { nodes, materials } = useGLTF(
    require("../../assets/models/ixora.glb")
  ) as any;

  // ตั้งค่า animation ให้หมุนทีละนิด
  useEffect(() => {
    y.value = withTiming(2, { duration: 2000 });
  }, []);

  useFrame(() => {
    if (group.current) {
      group.current.rotation.set(0, y.value, 0);
    }
  });

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_leaf_01b_0.geometry} material={materials.Ixora_leaf_01b} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_flower_01_0.geometry} material={materials.Ixora_flower_01} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_tube_0.geometry} material={materials.Ixora_tube} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_flower_stalk_2_0.geometry} material={materials.Ixora_flower_stalk_2} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_flower_02_0.geometry} material={materials.Ixora_flower_02} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_flower_03_0.geometry} material={materials.Ixora_flower_03} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_leaf_01e_0.geometry} material={materials.Ixora_leaf_01e} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_leaf_01f_0.geometry} material={materials.Ixora_leaf_01f} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_branches_0.geometry} material={materials.Ixora_branches} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_bud_0.geometry} material={materials.Ixora_bud} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_flower_stalk_1_0.geometry} material={materials.Ixora_flower_stalk_1} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_twig_0.geometry} material={materials.Ixora_twig} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_leaf_01d_0.geometry} material={materials.Ixora_leaf_01d} />
        <mesh geometry={nodes.Ixora_chinensis_red_HD_Ixora_leaf_01a_0.geometry} material={materials.Ixora_leaf_01a} />
      </group>
    </group>
  );
};

export default Sunflower;


// โหลดโมเดลล่วงหน้า
useGLTF.preload(require("../../assets/models/ixora.glb"));






/////// ปรับแต่งให้โมเดลไม่ใหญ่เกินไป model ขึ้นแล้ว แต่โมเดลใหญ่เกินไป
///ทำให้ model สามารถกดได้แล้วแสดงโครงงสร้างต่างๆของพืช