/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Source: https://sketchfab.com/3d-models/sunflower-3a9514b8df044abe809432201b8f1c6e
*/

import * as THREE from "three";
import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber/native";
import { useSharedValue, withTiming } from "react-native-reanimated";

const Sunflower = (props: any) => {
  const { onFlowerClick, ...rest } = props;
  const y = useSharedValue(0);
  const group = useRef<THREE.Group>(null);

  // โหลดโมเดล sunflower.glb
  const { nodes, materials } = useGLTF(
    require("../../assets/models/sunflower.glb")
  ) as any;

  // ตั้งค่า animation ให้หมุนทีละนิด
  useEffect(() => {
    y.value = withTiming(2, { duration: 2000 });
  }, []);

  useFrame(() => {
    if (group.current) {
      group.current.rotation.set(0, y.value, 0);
    }
  });

  return (
    <group ref={group} {...rest} dispose={null} position={[0, -3.5, -0.5]} scale={0.03}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.lambert2SG}
        rotation={[-Math.PI / 2, 0, 0]}
        castShadow
        receiveShadow
        onPointerDown={() =>
          alert("🌻 ดอกทานตะวัน: มีถิ่นกำเนิดในอเมริกาเหนือ ใช้ทำอาหารและน้ำมัน")
        }
      />
    </group>
  );
};

export default Sunflower;


// โหลดโมเดลล่วงหน้า
useGLTF.preload(require("../../assets/models/sunflower.glb"));






/////// ปรับแต่งให้โมเดลไม่ใหญ่เกินไป model ขึ้นแล้ว แต่โมเดลใหญ่เกินไป
///ทำให้ model สามารถกดได้แล้วแสดงโครงงสร้างต่างๆของพืช