/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sunflow.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sunflow.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert2SG} />
        <mesh geometry={nodes.Object_2001.geometry} material={materials.lambert2SG} />
        <mesh geometry={nodes.Object_2002.geometry} material={materials.lambert2SG} />
        <mesh geometry={nodes.Object_2003.geometry} material={materials.lambert2SG} />
        <mesh geometry={nodes.Object_2004.geometry} material={materials.lambert2SG} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/sunflow.glb')
