/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Source: https://sketchfab.com/3d-models/sunflower-3a9514b8df044abe809432201b8f1c6e
*/

import * as THREE from "three";
import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber/native";
import { useSharedValue, withTiming } from "react-native-reanimated";

const Sunflower = (props: any) => {
  const { onFlowerClick, ...rest } = props;
  const y = useSharedValue(0);
  const group = useRef<THREE.Group>(null);

  // โหลดโมเดล sunflower.glb
  const { nodes, materials } = useGLTF(
    require("../../assets/models/tulip.glb")
  ) as any;

  // ตั้งค่า animation ให้หมุนทีละนิด
  useEffect(() => {
    y.value = withTiming(2, { duration: 2000 });
  }, []);

  useFrame(() => {
    if (group.current) {
      group.current.rotation.set(0, y.value, 0);
    }
  });

  return (
    <group ref={group} {...rest} dispose={null} scale={0.001}>
        <group position={[-16.207, 0.06, -31.652]} rotation={[-1.463, -0.068, -0.304]} scale={100}>
          <mesh geometry={nodes.Cylinder002_tulip_opague_1_0.geometry} material={materials.tulip_opague_1} />
          <mesh geometry={nodes.Cylinder002_tulip_transparent_1_0.geometry} material={materials.tulip_transparent_1} />
        </group>
        <group position={[169.141, 0.06, -31.652]} rotation={[-1.602, 0.104, 0.953]} scale={100}>
          <mesh geometry={nodes.Cylinder001_tulip_opague_1_0.geometry} material={materials.tulip_opague_1} />
          <mesh geometry={nodes.Cylinder001_tulip_transparent_1_0.geometry} material={materials.tulip_transparent_1} />
        </group>
    </group>
  );
};

export default Sunflower;


// โหลดโมเดลล่วงหน้า
useGLTF.preload(require("../../assets/models/sunflower.glb"));






/////// ปรับแต่งให้โมเดลไม่ใหญ่เกินไป model ขึ้นแล้ว แต่โมเดลใหญ่เกินไป
///ทำให้ model สามารถกดได้แล้วแสดงโครงงสร้างต่างๆของพืช